// ui/theme/Color.kt

package com.FlashStudy.ui.theme

import androidx.compose.ui.graphics.Color

// Novas Cores para o Tema Claro
val md_theme_light_primary = Color(0xFF006D3D)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF9AF6B7)
val md_theme_light_onPrimaryContainer = Color(0xFF00210E)
val md_theme_light_secondary = Color(0xFF4F6353)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD2E8D4)
val md_theme_light_onSecondaryContainer = Color(0xFF0D1F13)
val md_theme_light_tertiary = Color(0xFF3C6472)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC0E9FA)
val md_theme_light_onTertiaryContainer = Color(0xFF001F28)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFDF7)
val md_theme_light_onBackground = Color(0xFF1A1C1A)
val md_theme_light_surface = Color(0xFFFCFDF7)
val md_theme_light_onSurface = Color(0xFF1A1C1A)
val md_theme_light_surfaceVariant = Color(0xFFDDE5DA)
val md_theme_light_onSurfaceVariant = Color(0xFF414942)
val md_theme_light_outline = Color(0xFF717971)

// Novas Cores para o Tema Escuro
val md_theme_dark_primary = Color(0xFF7EDA9E)
val md_theme_dark_onPrimary = Color(0xFF00391C)
val md_theme_dark_primaryContainer = Color(0xFF00522B)
val md_theme_dark_onPrimaryContainer = Color(0xFF9AF6B7)
val md_theme_dark_secondary = Color(0xFFB6CCB8)
val md_theme_dark_onSecondary = Color(0xFF223527)
val md_theme_dark_secondaryContainer = Color(0xFF384B3D)
val md_theme_dark_onSecondaryContainer = Color(0xFFD2E8D4)
val md_theme_dark_tertiary = Color(0xFFA4CDDE)
val md_theme_dark_onTertiary = Color(0xFF053542)
val md_theme_dark_tertiaryContainer = Color(0xFF234C59)
val md_theme_dark_onTertiaryContainer = Color(0xFFC0E9FA)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1A)
val md_theme_dark_onBackground = Color(0xFFE2E3DE)
val md_theme_dark_surface = Color(0xFF1A1C1A)
val md_theme_dark_onSurface = Color(0xFFE2E3DE)
val md_theme_dark_surfaceVariant = Color(0xFF414942)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C9BF)
val md_theme_dark_outline = Color(0xFF8B938A)